[package]
name = "delta"
version = "0.0.3"
authors = ["Dan Davison <dandavison7@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"
atty = "0.2.13"
box_drawing = "0.1.2"
console = "0.7.7"
shell-words = "0.1.0"
structopt = "0.2.16"
syntect = "3.2"
unicode-segmentation = "1.3.0"

[dependencies.error-chain]
version = "0.12"
default-features = false
features = []
